### ISSUE TITLE
Homepage README code sample results in 401 using OAuth tokens

### ISSUE THREAD

**Issue by notsoluckycharm** [Clever/clever-python#49]
Spent a bit of time going through the codebase to figure it out and I'm sharing this to potentially help others. I couldn't get it to work as advertised despite my tokens working in the API Explorer.

https://github.com/Clever/clever-python/blob/f2c31bd1b51cecb6930c961532fffebd75355faa/docs/DataApi.md 

the configuration needs to be 
```
# Configure OAuth2 access token for authorization: oauth
configuration = clever.Configuration()
configuration.access_token = 'YOUR_ACCESS_TOKEN'

# create an instance of the API class
api_instance = clever.DataApi(clever.ApiClient(configuration))
```

**Comment by meliaj** [comment]
Thank you for sharing this! I will update the readme.
