### ISSUE TITLE
PyPI packages for 3.0.0?

### ISSUE THREAD

**Issue by tony** [Clever/clever-python#51]
Hi there!

I'm trying to make sense of the API at the moment, and trying to see if this library makes it a bit easier to traverse a user's data.

The docs mention and use the ["clever" PyPI package](https://pypi.org/project/clever/). The latest version released here as of May 14th, 2018 is [2.4.0](https://pypi.org/project/clever/#history). As of today, the instructions on the README, the [latest tag](https://github.com/Clever/clever-python/tree/v3.0.0), are all based around 3.0.0.

It seems the 3.0 package is at "clever-python" https://pypi.org/project/clever-python, which targets 2.0 of the clever API.

Is https://pypi.org/project/clever-python/ the official package now? Or was 3.0.0 pushed by mistake to clever-python instead of clever (I think you have the clever package name on PyPI, right?) I'm not 100% if I'm overlooking something obvious. I think the intention may have been to expect would 3.0.0 being in the clever package?

Is 3.0.0 ready to use via clever-python in the mean time? The authors on PyPI are different.

**Comment by meliaj** [comment]
Hi there!

As of today https://pypi.org/project/clever-python/ is the latest official package. I will look into getting the latest pushed to the clever package as well, as we own them both.

**Comment by tony** [comment]
@meliaj Thank you over there! :+1:
