### ISSUE TITLE
python 3(.7) support

### ISSUE THREAD

**Issue by thierryba** [Clever/clever-python#56]
I had complained in the past that python 3 is not supported but with v2, I provided a patch and now with v3 it is broken again
among other things you can't do "import event" but "from . import event"
 and then async is a keyword

  File "..../python/lib/python3.7/site-packages/clever/apis/data_api.py", line 124
    async=params.get('async'),
        ^
SyntaxError: invalid syntax

Everybody else is moving to python3. Are there any plans for clever?
At this point I need to go back to clever 2.4

**Comment by meliaj** [comment]
Hi @thierryba - we use swagger-codegen to generate our client libraries from our swagger API file.

It looks like this is a known issue which has not been resolved yet: https://github.com/swagger-api/swagger-codegen/issues/8328

**Comment by thierryba** [comment]
apparently this was fixed now 
https://github.com/flywheel-io/core/pull/1345

**Comment by meliaj** [comment]
It looks like they fixed it manually.

**Comment by meliaj** [comment]
@thierryba are you able to try this branch to see if it works for you? https://github.com/Clever/clever-python/pull/58

**Comment by incidentist** [comment]
@meliaj That branch worked for me. Until that patch is released, this library will not install or run on Python 3.7 and above, but does run on 3.6.
