### ISSUE TITLE
3.0.2 on PyPi

### ISSUE THREAD

**Issue by youcandanch** [Clever/clever-python#59]
Hey y'all,

Looks like 3.0.1 is the most recent version on both https://pypi.org/project/clever-python/ and https://pypi.org/project/clever/. Any chance we can get an update on those for 3.0.2? We're moving our application to Py3.6 and we can't do that until the fix in #53 is available. @meliaj seems like this might be your turf.

**Comment by meliaj** [comment]
Apologies @youcandanch - I thought I had already done this. It is published now

**Comment by youcandanch** [comment]
Thank you!
