### ISSUE TITLE
Grade 13 breaks high grade check

### ISSUE THREAD

**Issue by shaleh** [Clever/clever-python#62]
We have reports from users of the grade being "13" but this breaks here

https://github.com/Clever/clever-python/blob/d452489a8b3fc24090a9361056aa6131d9fdf893/clever/models/school.py#L177

We see the following exception in our code using the Clever API:

```
ValueError
Invalid value for `high_grade` (13), must be one of ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', 'PreKindergarten', 'Kindergarten', 'PostGraduate', 'Other']
```

We are using version 3.0.2.

**Comment by meliaj** [comment]
@shaleh by any chance have you modified the library to pull from API version 2.1? These values should only be appearing in that version.

If so, the library needs to be updated to handle that value.

**Comment by shaleh** [comment]
We have made no changes. This is 100% stock pulled from pip.

**Comment by shaleh** [comment]
Is 2.1 access based on the keys we are using?

**Comment by meliaj** [comment]
@shaleh we've opened a ticket with our partner engineering team. I believe we've found the issue and hope to have fixed it later today

**Comment by meliaj** [comment]
@shaleh we've deployed a fix for this and you should not be seeing Grade 13 any more. Please let us know if you have any further issues.

**Comment by shaleh** [comment]
@meliaj thank you for the rapid responses.

**Comment by shaleh** [comment]
Confirmed. Thank you.
