### ISSUE TITLE
Error running `pip install clever`

### ISSUE THREAD

**Issue by zeninfinity** [Clever/clever-python#67]
$ pip install clever
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting clever
  Downloading clever-3.0.2.tar.gz (43 kB)
     |████████████████████████████████| 43 kB 2.1 MB/s
ERROR: More than one .egg-info directory found in /tmp/pip-pip-egg-info-5qwoGa
$

**Comment by incidentist** [comment]
This library appears to be incompatible with newer versions of pip. The following worked for me:
```
> pip install pip==20.0.1
> rm -rf $(pip cache dir)
> pip install clever
```
Some relevant info here: https://github.com/pypa/pip/issues/8201

**Comment by zeninfinity** [comment]
Thanks for the response @incidentist .

ZZ

**Comment by benjaminlong** [comment]
Hello, 
I juste reached this issue.
Are you planning on updating the `setup.py` file with only one setup call to match pip requirements ?
Any other workaround ?
Best,
